language: node_js

# Use container-based infrastructure
sudo: false

node_js:
  - "node" # latest stable Node.js release
  - "7"

install:
  - yarn global add codeclimate-test-reporter
  - yarn --frozen-lockfile

script:
  - yarn run ci

after_script:
  - CODECLIMATE_REPO_TOKEN=bd7a28a7dc9fa40d5ed03ab1ae441cae7969b62a19001c59685605986ff2a19c codeclimate-test-reporter < coverage/lcov.info

addons:
    code_climate:
        repo_token: bd7a28a7dc9fa40d5ed03ab1ae441cae7969b62a19001c59685605986ff2a19c
